<?php

session_start();

if(!isset($_REQUEST["id"])){
	header("Location: ./");
	die;
}

if(!isset($_SESSION["access_token"])){
	header("Location: ./");
}

function urlGet($url){
	$ch = curl_init($url);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
	curl_setopt($ch, CURLOPT_FORBID_REUSE, 1);
	curl_setopt($ch, CURLOPT_FRESH_CONNECT, 1);
	curl_setopt($ch, CURLOPT_AUTOREFERER, true);
	curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
	curl_setopt($ch, CURLOPT_HTTPHEADER, ["User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0 pmt.mcpe.me-insta/1.0", "Authorization: bearer " . $_SESSION["access_token"]]);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
	curl_setopt($ch, CURLOPT_TIMEOUT, 5);
	$result = curl_exec($ch);
	curl_close($ch);
	return $result;
}

$gist = json_decode($json = urlGet("https://api.github.com/gists/" . $_REQUEST["id"]));
if(isset($gist->message) and $gist->message === "Not Found"){
	echo "Gist Not Found!";
	die;
}

$files = $gist->files;
$phar = new Phar($path = "data/" . ($identifier = str_replace(["=", "+", "/"], "_", base64_encode(openssl_random_pseudo_bytes(8)))) . ".phar");
$phar->startBuffering();
$phar->setStub("<?php __HALT_COMPILER();");
$phar->setSignatureAlgorithm(Phar::SHA512);
foreach($gist->files as $name => $file){
	$content = $file->content;
	$phar->addFromString(str_replace("--", "/", $name), $content);
}
$phar->addFromString("me.mcpe.pmt.insta.watermark", "This file is generated by pmt.mcpe.me/insta/ from https://gist.github.com/" . $_REQUEST["id"] . ", build ID $identifier, at " . date(DATE_ISO8601));
$phar->stopBuffering();

if(isset($_SERVER["HTTP_ACCEPT"]) and $_SERVER["HTTP_ACCEPT"] === "application/json"){
	echo json_encode([
		"phar" => "http://pmt.mcpe.me/insta/$path",
		"source" => "https://gist.github.com/" . $_REQUEST["id"]
	]);
}
?>
<html>
<head>
	<title>InstaPlugin</title>
	<script src="//code.jquery.com/jquery-1.10.2.min.js"></script><script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script><link href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.min.css" rel="stylesheet" />
	<style type="text/css" rel="stylesheet">
		<?= file_get_contents("style.css") ?>
	</style>
	<script>
		<?= file_get_contents("style.js") ?>
	</script>
</head>
<body>
<h1 class="title">Plugin created.</h1>
<p><a href="<?= $path ?>">Download link</a></p>
<p>
	BB code: (according to XenForo standards)
	<?php
	$lines = [
		"[spoiler=\"Source code\"][media=gist]" . $_REQUEST["id"] . "[/media][/spoiler]",
		"[spoiler=\"Phar download\"][url=\"http://pmt.mcpe.me/insta/$path\"]Download plugin from pmt.mcpe.me[/url]",
		"Generated by [url=\"http://pmt.mcpe.me/insta/\"]pmt.mcpe.me Gist2Plugin instant plugin maker[/url][/spoiler]"
	];
	?>
	<textarea rows="2" cols="<?= max(array_map("strlen", $lines)) ?>"><?= implode("\r\n", array_map("htmlspecialchars", $lines)) ?></textarea>
</p>
</body>
</html>
